export const SIGNUP_PAGE_SIGNUP_FORM_FIELD_CHANGE = 'SIGNUP_PAGE_SIGNUP_FORM_FIELD_CHANGE';
export const SIGNUP_PAGE_SIGNIN_FORM_FIELD_CHANGE = 'SIGNUP_PAGE_SIGNIN_FORM_FIELD_CHANGE';

export const SIGNUP_PAGE_SIGNUP_REQUEST = 'SIGNUP_PAGE_SIGNUP_REQUEST';
export const SIGNUP_PAGE_SIGNUP_REQUEST_SUCCESS = 'SIGNUP_PAGE_SIGNUP_REQUEST_SUCCESS';
export const SIGNUP_PAGE_SIGNUP_REQUEST_ERROR = 'SIGNUP_PAGE_SIGNUP_REQUEST_ERROR';

export const SIGNUP_PAGE_SIGNIN_REQUEST = 'SIGNUP_PAGE_SIGNIN_REQUEST';
export const SIGNUP_PAGE_SIGNIN_REQUEST_SUCCESS = 'SIGNUP_PAGE_SIGNIN_REQUEST_SUCCESS';
export const SIGNUP_PAGE_SIGNIN_REQUEST_ERROR = 'SIGNUP_PAGE_SIGNIN_REQUEST_ERROR';
