export const SIGNIN_REQUEST = 'SIGNIN_REQUEST';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const SIGNUP_PAGE_SIGNIN_FORM_EMAIL_CHANGE = 'SIGNUP_PAGE_SIGNIN_FORM_EMAIL_CHANGE';
export const SIGNUP_PAGE_SIGNIN_FORM_PASSWORD_CHANGE = 'SIGNUP_PAGE_SIGNIN_FORM_PASSWORD_CHANGE';
export const SIGNUP_PAGE_SIGNUP_FORM_FULL_NAME_CHANGE = 'SIGNUP_PAGE_SIGNUP_FORM_FULL_NAME_CHANGE';
export const SIGNUP_PAGE_SIGNUP_FORM_EMAIL_CHANGE = 'SIGNUP_PAGE_SIGNUP_FORM_EMAIL_CHANGE';
export const SIGNUP_PAGE_SIGNUP_FORM_PASSWORD_CHANGE = 'SIGNUP_PAGE_SIGNUP_FORM_PASSWORD_CHANGE';

export const ON_FORM_FIELD_CHANGE = 'ON_FORM_FIELD_CHANGE';